server:
  port: 80
  servlet:
    context-path: /board
    
spring:
#  config:
#    activate:
#      on-profile: dev  
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://127.0.0.1:3306/board?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true 
  thymeleaf:
      cache: false

file:
  upload-dir: C:\Users\user\Desktop\우리fisa 강의내용\프로젝트 모음\bulletin_board\Bulletin_board\src\main\resources\static\uploads



thymeleaf:
  cache: false
  check-template-location: true
  enabled: true
  prefix: classpath:/templates/
  suffix: .html
#    view-names: /*

logging:
  level:
    root: info  # 루트 로그 레벨을 info로 설정
    edu.fisa.board.controller: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"  # 콘솔에 출력할 로그 패턴 설정
  file:
    name: myapp.log  # 로그 파일 이름 설정
    path: /var/log/myapp  # 로그 파일 경로 설정